// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqIqSwoWwdb2mMVOG387Ofr0PxP2ajeJ4',
    appId: '1:769931799625:web:caea5b026537432a51e398',
    messagingSenderId: '769931799625',
    projectId: 'safeher-app-9251b',
    authDomain: 'safeher-app-9251b.firebaseapp.com',
    storageBucket: 'safeher-app-9251b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhy87eKu3ojZf3AMs9xx-aPT6jmPtonQU',
    appId: '1:769931799625:android:48bdbf01dbe4d6f451e398',
    messagingSenderId: '769931799625',
    projectId: 'safeher-app-9251b',
    storageBucket: 'safeher-app-9251b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_KL6M9k16Ti_L4v_n9bdiJjjd9Kidso',
    appId: '1:769931799625:ios:b3a51b3726cff49b51e398',
    messagingSenderId: '769931799625',
    projectId: 'safeher-app-9251b',
    storageBucket: 'safeher-app-9251b.firebasestorage.app',
    iosBundleId: 'com.example.safeher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB_KL6M9k16Ti_L4v_n9bdiJjjd9Kidso',
    appId: '1:769931799625:ios:b3a51b3726cff49b51e398',
    messagingSenderId: '769931799625',
    projectId: 'safeher-app-9251b',
    storageBucket: 'safeher-app-9251b.firebasestorage.app',
    iosBundleId: 'com.example.safeher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqIqSwoWwdb2mMVOG387Ofr0PxP2ajeJ4',
    appId: '1:769931799625:web:8edc438a38120a3f51e398',
    messagingSenderId: '769931799625',
    projectId: 'safeher-app-9251b',
    authDomain: 'safeher-app-9251b.firebaseapp.com',
    storageBucket: 'safeher-app-9251b.firebasestorage.app',
  );
}
